name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    environment: Production 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint python-keycloak faker psycopg2-binary

      - name: Run pylint
        run: |
          pylint app --fail-under=8.0

      - name: SSH to the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_DOMAIN }}
          username: ${{ vars.SERVER_CICD_USER }}
          key: ${{ secrets.SERVER_CICD_SSH_KEY }}

          script: |
            cd /home/cicd/openfincal

            make prod-down

            git pull origin main

            make prod
